### ISSUE TITLE
Example of how use OpenSSL random generator

### ISSUE THREAD

**Issue by Mararok** [mcmikecreations/nanoid_cpp#2]
How implement openssl secure generator ?

**Comment by mcmikecreations** [comment]
Hi! I've added a simple OpenSSL example in the [latest commit](https://github.com/mcmikecreations/nanoid_cpp/blob/ef5c8a3d198588aa0c07286eaee6ad8d90f06de2/examples/openssl/openssl.cpp). You need to declare a new class that utilizes the random generator you want, override a few methods and pass it to `nanoid`. You can also use OpenSSL engines, pseudo-random generation, etc. within this class. 

So keep in mind that this is the simplest example possible. In reality, you would probably want to use a [Hardware Engine](https://wiki.openssl.org/index.php/Random_Numbers#Hardware).

If you're using an old OpenSSL version, you'd also need to use [`CRYPTO_set_locking_callback`](https://www.openssl.org/docs/man1.0.2/man3/CRYPTO_set_locking_callback.html) to achieve thread-safety.

**Comment by Mararok** [comment]
Awesome !!! Thx 😍
